[project]
name = "openai-agents-sdk-decoded"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.96.1",
    "openai-agents[litellm]>=0.0.19",
    "python-dotenv>=1.1.1",
]
